import fs from 'fs';
import path from 'path';

const CAFE_FILE = path.join(process.cwd(), 'src', 'data', 'spots', 'cafe.json');

const newCafes = [
  {
    "id": 14,
    "name": "The Workshop Coffee",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "27 Ngô Đức Kế, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "27 Ngô Đức Kế, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Specialty Coffee",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "100k-200k",
    "rating": 4.4,
    "reviews": 4103,
    "hours": "08:00 - 20:30",
    "phone": "02838246801",
    "goodReview": "Không gian hiện đại, rộng rãi, phù hợp gặp gỡ và làm việc.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Specialty Coffee", "Deadline", "Date", "Work-friendly"],
    "desc": "The Workshop Coffee là specialty coffee nổi tiếng tại trung tâm Quận 1, phù hợp vừa trò chuyện vừa làm việc.",
    "images": [],
    "quickActions": ["Chạy deadline", "Hẹn hò", "Uống specialty coffee"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJdyfroEYvdTER2m7eTz44Bns",
    "mapUrl": ""
  },
  {
    "id": 15,
    "name": "Soo Kafe Bến Thành",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "35 Phan Chu Trinh, Bến Thành, Quận 1, Hồ Chí Minh",
    "fullAddress": "35 Phan Chu Trinh, Bến Thành, Quận 1, Hồ Chí Minh",
    "tag": "Cafe làm việc",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.6,
    "reviews": 2010,
    "hours": "08:00 - 23:00",
    "phone": "0899312386",
    "goodReview": "Không gian rộng, có khu vực phù hợp học tập và hoàn thành deadline.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Deadline", "Work-friendly", "Cafe", "Date"],
    "desc": "Soo Kafe có không gian hai tầng, phù hợp cả làm việc lẫn trò chuyện.",
    "images": [],
    "quickActions": ["Chạy deadline", "Hẹn hò", "Làm việc"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJLUnNLj8vdTERtZ0FtgSj9-A",
    "mapUrl": ""
  },
  {
    "id": 16,
    "name": "Whisfee Café",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "14 Tôn Thất Đạm, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "14 Tôn Thất Đạm, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe chill",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.8,
    "reviews": 327,
    "hours": "09:00 - 23:00",
    "phone": "0356725601",
    "goodReview": "Không gian chill, rating cao, phù hợp nói chuyện và hẹn hò.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "Chill", "Cafe", "Check-in"],
    "desc": "Whisfee Café là quán cafe có không gian phù hợp cho những buổi hẹn và trò chuyện.",
    "images": [],
    "quickActions": ["Hẹn hò", "Nói chuyện", "Check-in"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJDz8w4xsvdTERw4Y9lMhqLQ0",
    "mapUrl": ""
  },
  {
    "id": 17,
    "name": "L'Usine Lê Thánh Tôn",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "19 Lê Thánh Tôn, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "19 Lê Thánh Tôn, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe & lifestyle",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "100k-300k",
    "rating": 4.6,
    "reviews": 3402,
    "hours": "07:30 - 21:30",
    "phone": "0832810888",
    "goodReview": "Không gian đẹp, có thể làm việc và gặp gỡ trong khu trung tâm.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Deadline", "Date", "Lifestyle", "Cafe"],
    "desc": "L'Usine kết hợp cafe, ẩm thực và lifestyle với không gian phù hợp làm việc hoặc gặp gỡ.",
    "images": [],
    "quickActions": ["Chạy deadline", "Hẹn hò", "Ăn nhẹ"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJmSbv60gvdTER8Nqtg6Unzpw",
    "mapUrl": ""
  },
  {
    "id": 18,
    "name": "Tonkin Specialty Coffee",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "91 Lý Tự Trọng, Bến Thành, Quận 1, Hồ Chí Minh",
    "fullAddress": "91 Lý Tự Trọng, Bến Thành, Quận 1, Hồ Chí Minh",
    "tag": "Specialty Coffee",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.8,
    "reviews": 4620,
    "hours": "08:00 - 21:00",
    "phone": "0867990125",
    "goodReview": "Specialty coffee được đánh giá cao, phù hợp ngồi trò chuyện hoặc làm việc.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Specialty Coffee", "Date", "Deadline", "Coffee"],
    "desc": "Tonkin Specialty Coffee là quán specialty coffee có rating cao tại Lý Tự Trọng.",
    "images": [],
    "quickActions": ["Uống coffee", "Hẹn hò", "Làm việc"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJzaevQMcvdTERYE3UhLKg5NE",
    "mapUrl": ""
  },
  {
    "id": 19,
    "name": "OKKIO Lê Lợi",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "120-122 Lê Lợi, Bến Thành, Quận 1, Hồ Chí Minh",
    "fullAddress": "120-122 Lê Lợi, Bến Thành, Quận 1, Hồ Chí Minh",
    "tag": "Specialty Coffee",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.6,
    "reviews": 1277,
    "hours": "07:30 - 20:00",
    "phone": "0848011118",
    "goodReview": "Chuỗi cafe specialty có không gian hiện đại, thuận tiện gặp gỡ và làm việc.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Deadline", "Date", "Specialty Coffee"],
    "desc": "OKKIO Lê Lợi là một lựa chọn cafe trung tâm, phù hợp cả công việc và hẹn hò.",
    "images": [],
    "quickActions": ["Chạy deadline", "Hẹn hò", "Coffee"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJcUtJy3wvdTERQIZ4d5vBYS8",
    "mapUrl": ""
  },
  {
    "id": 20,
    "name": "Hoff Coffee Brewers by BeanHop",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "42bis Lý Tự Trọng, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "42bis Lý Tự Trọng, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Specialty Coffee",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.8,
    "reviews": 356,
    "hours": "07:30 - 21:00",
    "phone": "0989984506",
    "goodReview": "Quán specialty coffee được đánh giá cao, phù hợp coffee date và làm việc nhẹ.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Specialty Coffee", "Date", "Deadline"],
    "desc": "Hoff Coffee Brewers by BeanHop là specialty coffee tại Lý Tự Trọng.",
    "images": [],
    "quickActions": ["Coffee date", "Làm việc", "Check-in"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJ3SIDkK4vdTERET6eDRYrDyE",
    "mapUrl": ""
  },
  {
    "id": 21,
    "name": "The Running Bean - Mạc Thị Bưởi",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "33 Mạc Thị Bưởi, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "33 Mạc Thị Bưởi, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe & brunch",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "100k-300k",
    "rating": 4.7,
    "reviews": 3344,
    "hours": "07:30 - 22:00",
    "phone": "02873003633",
    "goodReview": "Không gian hiện đại, phù hợp ăn nhẹ, trò chuyện và làm việc.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "Brunch", "Deadline", "Cafe"],
    "desc": "The Running Bean là cafe kết hợp đồ ăn và không gian hiện đại tại trung tâm Quận 1.",
    "images": [],
    "quickActions": ["Hẹn hò", "Brunch", "Chạy deadline"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJbZibl2QvdTERpAnl0Vxjk5Q",
    "mapUrl": ""
  },
  {
    "id": 22,
    "name": "BẢN Cà Phê",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "38/7 Lê Lợi, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "38/7 Lê Lợi, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe chill",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.6,
    "reviews": 598,
    "hours": "08:00 - 22:00",
    "phone": "028666726936",
    "goodReview": "Không gian cafe được đánh giá tốt, phù hợp ngồi lâu và trò chuyện.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "Chill", "Deadline"],
    "desc": "BẢN Cà Phê nằm trong khu trung tâm, phù hợp cho một buổi coffee date hoặc làm việc.",
    "images": [],
    "quickActions": ["Hẹn hò", "Làm việc", "Nói chuyện"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJnQ0nfLEvdTERGAOqj06KUQY",
    "mapUrl": ""
  },
  {
    "id": 23,
    "name": "Sài Gòn Ơi",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "42 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "42 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe view phố",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.1,
    "reviews": 818,
    "hours": "07:00 - 23:00",
    "phone": "",
    "goodReview": "Cafe trong chung cư 42 Nguyễn Huệ, phù hợp ngắm phố và trò chuyện.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "View phố", "Check-in", "Cafe"],
    "desc": "Sài Gòn Ơi là một trong những cafe nổi tiếng tại chung cư 42 Nguyễn Huệ.",
    "images": [],
    "quickActions": ["Hẹn hò", "Ngắm phố", "Check-in"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJw7k36kYvdTERJ9L8Dd7o-0U",
    "mapUrl": ""
  },
  {
    "id": 24,
    "name": "Starbucks Nguyễn Huệ",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "99 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "99 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe chuỗi",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "100k-200k",
    "rating": 4.3,
    "reviews": 1410,
    "hours": "06:30 - 23:00",
    "phone": "02838210105",
    "goodReview": "Không gian quen thuộc, tiện ngồi làm việc hoặc gặp gỡ.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Deadline", "Date", "Wifi", "Cafe"],
    "desc": "Starbucks Nguyễn Huệ là lựa chọn ổn định cho gặp gỡ hoặc làm việc tại trung tâm.",
    "images": [],
    "quickActions": ["Chạy deadline", "Hẹn hò", "Làm việc"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJZyg9xkYvdTEReQjhF2Md4Yw",
    "mapUrl": ""
  },
  {
    "id": 25,
    "name": "% Arabica Nguyễn Huệ",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "42 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "42 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Specialty Coffee",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "100k-200k",
    "rating": 4.2,
    "reviews": 4111,
    "hours": "07:00 - 23:00",
    "phone": "02835355380",
    "goodReview": "Thương hiệu specialty coffee quốc tế tại chung cư 42 Nguyễn Huệ.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Specialty Coffee", "Date", "Check-in"],
    "desc": "% Arabica tại Nguyễn Huệ phù hợp coffee date và trải nghiệm cafe trong khu chung cư nổi tiếng.",
    "images": [],
    "quickActions": ["Coffee date", "Check-in", "Ngắm phố"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJY41T6kYvdTERS92294dJ1J4",
    "mapUrl": ""
  },
  {
    "id": 26,
    "name": "Meraki Café",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "Chung cư 42 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "Chung cư 42 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe chung cư",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.1,
    "reviews": 733,
    "hours": "08:00 - 23:30",
    "phone": "0977079305",
    "goodReview": "Cafe trong chung cư 42 Nguyễn Huệ, thuận tiện kết hợp đi dạo phố Nguyễn Huệ.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "Check-in", "View phố", "Cafe"],
    "desc": "Meraki Café nằm trong chung cư 42 Nguyễn Huệ, phù hợp một buổi hẹn kết hợp dạo phố.",
    "images": [],
    "quickActions": ["Hẹn hò", "Check-in", "Đi dạo"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJTUZSCYEvdTERvDobmn4HwqM",
    "mapUrl": ""
  },
  {
    "id": 27,
    "name": "The Letter Cafe",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "42 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "42 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Rooftop Cafe",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 3.1,
    "reviews": 210,
    "hours": "09:00 - 22:30",
    "phone": "0795807950",
    "goodReview": "Không gian trên cao trong khu chung cư 42 Nguyễn Huệ, phù hợp ngắm phố và chụp ảnh.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Rooftop", "Date", "Check-in", "View phố"],
    "desc": "The Letter Cafe là lựa chọn thiên về view và trải nghiệm hơn là chạy deadline.",
    "images": [],
    "quickActions": ["Hẹn hò", "Check-in", "Ngắm phố"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJl0SDOdYvdTERnJQ91Vr8id4",
    "mapUrl": ""
  },
  {
    "id": 28,
    "name": "Lee's Coffee - Sài Gòn",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "84 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "84 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe trung tâm",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.5,
    "reviews": 97,
    "hours": "06:00 - 23:00",
    "phone": "18002218",
    "goodReview": "Mở cửa từ sáng sớm, phù hợp cả làm việc và hẹn gặp.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Deadline", "Date", "Nguyễn Huệ"],
    "desc": "Lee's Coffee nằm ngay Nguyễn Huệ và có thời gian hoạt động dài.",
    "images": [],
    "quickActions": ["Chạy deadline", "Hẹn hò", "Ngắm phố"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJ09GWD-kvdTERav3fc6dnj4U",
    "mapUrl": ""
  },
  {
    "id": 29,
    "name": "Blubean.",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "14 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "14 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe chill",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.9,
    "reviews": 82,
    "hours": "09:30 - 21:30",
    "phone": "0902941409",
    "goodReview": "Rating cao, phù hợp coffee date và ngồi trò chuyện.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "Chill", "Coffee", "Check-in"],
    "desc": "Blubean. là cafe nhỏ tại Nguyễn Huệ, phù hợp những buổi hẹn nhẹ nhàng.",
    "images": [],
    "quickActions": ["Hẹn hò", "Coffee date", "Check-in"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJ2cauAbovdTERtnXkDc4wM0U",
    "mapUrl": ""
  },
  {
    "id": 30,
    "name": "Trung Nguyên Legend - Nguyễn Huệ",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "68 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "68 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe thương hiệu",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "100k-200k",
    "rating": 5.0,
    "reviews": 301,
    "hours": "07:00 - 23:00",
    "phone": "0911129051",
    "goodReview": "Không gian thương hiệu cafe lớn, mở cửa dài và phù hợp gặp gỡ.",
    "badReview": "",
    "hasBad": false,
    "viewDep": false,
    "tags": ["Date", "Deadline", "Coffee", "Nguyễn Huệ"],
    "desc": "Trung Nguyên Legend trên Nguyễn Huệ phù hợp gặp gỡ hoặc làm việc trong khu trung tâm.",
    "images": [],
    "quickActions": ["Hẹn hò", "Chạy deadline", "Coffee"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJLWV6OpcvdTERb5QSZzQoRFE",
    "mapUrl": ""
  },
  {
    "id": 31,
    "name": "The Coffee Bean & Tea Leaf Nguyễn Huệ",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "101 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "101 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe chuỗi",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.2,
    "reviews": 652,
    "hours": "",
    "phone": "0703800823",
    "goodReview": "Chuỗi cafe quốc tế, phù hợp gặp gỡ và ngồi làm việc.",
    "badReview": "",
    "hasBad": false,
    "viewDep": false,
    "tags": ["Deadline", "Date", "Wifi", "Coffee"],
    "desc": "The Coffee Bean & Tea Leaf Nguyễn Huệ là lựa chọn quen thuộc cho làm việc hoặc gặp gỡ.",
    "images": [],
    "quickActions": ["Chạy deadline", "Hẹn hò", "Làm việc"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJCaWvxEYvdTERDs10fLc-Jyo",
    "mapUrl": ""
  },
  {
    "id": 32,
    "name": "Calibre Lounge",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "56-66 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "56-66 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe lounge",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "100k-500k",
    "rating": 4.5,
    "reviews": 54,
    "hours": "06:00 - 22:00",
    "phone": "0788805666",
    "goodReview": "Không gian lounge phù hợp gặp gỡ và trò chuyện.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "Lounge", "Coffee", "View phố"],
    "desc": "Calibre Lounge nằm trên Nguyễn Huệ, phù hợp cho một buổi hẹn hoặc gặp gỡ.",
    "images": [],
    "quickActions": ["Hẹn hò", "Nói chuyện", "Ngắm phố"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJpbe870YvdTERkLVv452gWQk",
    "mapUrl": ""
  },
  {
    "id": 33,
    "name": "Room44 Caffe",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "35 Nguyễn Văn Tráng, Bến Thành, Quận 1, Hồ Chí Minh",
    "fullAddress": "35 Nguyễn Văn Tráng, Bến Thành, Quận 1, Hồ Chí Minh",
    "tag": "Cafe chill",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.1,
    "reviews": 285,
    "hours": "08:00 - 22:00",
    "phone": "0906123495",
    "goodReview": "Không gian cafe phù hợp ngồi lâu và trò chuyện.",
    "badReview": "",
    "hasBad": false,
    "tags": ["Date", "Chill", "Deadline"],
    "desc": "Room44 Caffe là cafe tại Nguyễn Văn Tráng, phù hợp coffee date hoặc làm việc.",
    "images": [],
    "quickActions": ["Hẹn hò", "Chạy deadline", "Nói chuyện"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJO9v9sskvdTER4EBNw9XMplI",
    "mapUrl": ""
  },
  {
    "id": 34,
    "name": "Beanthere Cafe",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "42/7 Hồ Hảo Hớn, Cô Giang, Quận 1, Hồ Chí Minh",
    "fullAddress": "42/7 Hồ Hảo Hớn, Cô Giang, Quận 1, Hồ Chí Minh",
    "tag": "Cafe làm việc",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "60k-140k",
    "rating": null,
    "reviews": null,
    "hours": "09:00 - 22:00",
    "phone": "",
    "goodReview": "Không gian yên tĩnh, có nhiều ổ cắm, phù hợp học tập và chạy deadline.",
    "badReview": "",
    "hasBad": false,
    "tags": ["Deadline", "Yên tĩnh", "Work-friendly", "Cafe"],
    "desc": "Beanthere Cafe nằm trong khu chung cư cũ tại Hồ Hảo Hớn, nổi bật với không gian yên tĩnh và nhiều ổ cắm điện.",
    "images": [],
    "quickActions": ["Chạy deadline", "Học tập", "Làm việc"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 35,
    "name": "Cô Ba Đồng Khởi",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "4-6 Đồng Khởi, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "4-6 Đồng Khởi, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe view sông",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "100k+",
    "rating": null,
    "reviews": null,
    "hours": "07:30 - 23:00",
    "phone": "02838233196",
    "goodReview": "View hướng sông Sài Gòn, không gian trong nhà và ngoài trời phù hợp hẹn hò.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "View sông", "Check-in", "Cafe"],
    "desc": "Cô Ba Đồng Khởi là cafe có view hướng sông Sài Gòn, phù hợp cho coffee date.",
    "images": [],
    "quickActions": ["Hẹn hò", "Ngắm sông", "Check-in"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 36,
    "name": "Miyama - Modern Tokyo Restaurant Cafe",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe phong cách Nhật",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "100k+",
    "rating": null,
    "reviews": null,
    "hours": "",
    "phone": "",
    "goodReview": "Không gian hiện đại theo phong cách Tokyo, phù hợp hẹn hò và ăn nhẹ.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "Japanese", "Cafe", "Check-in"],
    "desc": "Miyama là mô hình cafe và restaurant phong cách Tokyo, phù hợp cho những buổi hẹn.",
    "images": [],
    "quickActions": ["Hẹn hò", "Ăn nhẹ", "Check-in"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 37,
    "name": "Saigon Oi Cafe",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "42 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "42 Nguyễn Huệ, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe view phố",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": 4.1,
    "reviews": 818,
    "hours": "07:00 - 23:00",
    "phone": "",
    "goodReview": "View Nguyễn Huệ, phù hợp ngắm phố và trò chuyện.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "View phố", "Check-in"],
    "desc": "Saigon Oi Cafe là lựa chọn phổ biến trong chung cư 42 Nguyễn Huệ.",
    "images": [],
    "quickActions": ["Hẹn hò", "Ngắm phố", "Check-in"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 38,
    "name": "Đen Đá Cafe - Pasteur",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "182 Pasteur, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "182 Pasteur, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe 24h",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": null,
    "reviews": null,
    "hours": "24/24",
    "phone": "",
    "goodReview": "Không gian thuận tiện cho làm việc khuya và gặp gỡ.",
    "badReview": "",
    "hasBad": false,
    "tags": ["24/7", "Deadline", "Date", "Cafe"],
    "desc": "Đen Đá Cafe tại Pasteur là lựa chọn phù hợp nếu cần một nơi có thể ngồi làm việc vào buổi tối hoặc khuya.",
    "images": [],
    "quickActions": ["Chạy deadline", "Làm việc khuya", "Hẹn hò"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 39,
    "name": "Khóm Coffee & Tea",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "5 Trần Quý Khoách, Tân Định, Quận 1, Hồ Chí Minh",
    "fullAddress": "5 Trần Quý Khoách, Tân Định, Quận 1, Hồ Chí Minh",
    "tag": "Cafe sân vườn",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "50k-120k",
    "rating": null,
    "reviews": null,
    "hours": "",
    "phone": "",
    "goodReview": "Không gian nhiều cây xanh, phù hợp trò chuyện và hẹn hò.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "Cây xanh", "Chill", "Cafe"],
    "desc": "Khóm Coffee & Tea là cafe có không gian nhiều cây xanh, phù hợp coffee date.",
    "images": [],
    "quickActions": ["Hẹn hò", "Nói chuyện", "Check-in"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 40,
    "name": "S'mores Saigon",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "47-49 Đặng Thị Nhu, Nguyễn Thái Bình, Quận 1, Hồ Chí Minh",
    "fullAddress": "47-49 Đặng Thị Nhu, Nguyễn Thái Bình, Quận 1, Hồ Chí Minh",
    "tag": "Cafe concept",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "50k-150k",
    "rating": null,
    "reviews": null,
    "hours": "",
    "phone": "",
    "goodReview": "Cafe concept độc đáo, phù hợp hẹn hò và chụp ảnh.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "Concept", "Check-in", "Cafe"],
    "desc": "S'mores Saigon là cafe concept phù hợp trải nghiệm và hẹn hò.",
    "images": [],
    "quickActions": ["Hẹn hò", "Check-in", "Nói chuyện"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 41,
    "name": "Heritage Indochine",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "151 Đồng Khởi, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "151 Đồng Khởi, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe Indochine",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "100k+",
    "rating": null,
    "reviews": null,
    "hours": "",
    "phone": "",
    "goodReview": "Không gian phong cách Indochine, thiên về trải nghiệm và hẹn hò.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "Indochine", "Check-in", "Cafe"],
    "desc": "Heritage Indochine là cafe mang phong cách Đông Dương, phù hợp cho một buổi hẹn có yếu tố trải nghiệm.",
    "images": [],
    "quickActions": ["Hẹn hò", "Check-in", "Nói chuyện"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 42,
    "name": "Cộng Cà Phê - Quận 1",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "26-28 Tôn Thất Thiệp, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "26-28 Tôn Thất Thiệp, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Cafe concept Việt",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "50k-100k",
    "rating": null,
    "reviews": null,
    "hours": "",
    "phone": "",
    "goodReview": "Concept Việt Nam đặc trưng, phù hợp trò chuyện và hẹn hò.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Date", "Concept", "Cafe", "Check-in"],
    "desc": "Cộng Cà Phê là chuỗi cafe có concept Việt Nam đặc trưng, phù hợp coffee date.",
    "images": [],
    "quickActions": ["Hẹn hò", "Nói chuyện", "Check-in"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 43,
    "name": "Soo Kafe - Phan Kế Bính",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "10 Phan Kế Bính, Đa Kao, Quận 1, Hồ Chí Minh",
    "fullAddress": "10 Phan Kế Bính, Đa Kao, Quận 1, Hồ Chí Minh",
    "tag": "Cafe làm việc",
    "tagClass": "tag-cafe",
    "category": "cafe",
    "price": "1-100k",
    "rating": null,
    "reviews": null,
    "hours": "08:00 - 23:00",
    "phone": "",
    "goodReview": "Không gian rộng, có tầng trên phù hợp học tập và hoàn thành deadline.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": ["Deadline", "Work-friendly", "Date", "Cafe"],
    "desc": "Soo Kafe Phan Kế Bính có không gian phù hợp làm việc, đồng thời vẫn thích hợp gặp gỡ.",
    "images": [],
    "quickActions": ["Chạy deadline", "Hẹn hò", "Làm việc"],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  }
];

const currentSpots = JSON.parse(fs.readFileSync(CAFE_FILE, 'utf8'));

// Filter out duplicate names if any
const existingNames = new Set(currentSpots.map(s => s.name.toLowerCase().trim()));
const filteredNewCafes = newCafes.filter(s => !existingNames.has(s.name.toLowerCase().trim()));

// Re-index
const combined = [...currentSpots, ...filteredNewCafes];
combined.forEach((s, idx) => {
  s.id = idx + 1;
});

fs.writeFileSync(CAFE_FILE, JSON.stringify(combined, null, 2), 'utf8');
console.log(`🎉 Combined cafe.json now has ${combined.length} total spots (${filteredNewCafes.length} new District 1 cafes added)!`);
