import fs from 'fs';
import path from 'path';

const GARDEN_FILE = path.join(process.cwd(), 'src', 'data', 'spots', 'garden.json');

const newGardens = [
  {
    "id": 19,
    "name": "Tiệm cây Người Làm Vườn",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "55 Sương Nguyệt Anh, Quận 1, Hồ Chí Minh",
    "fullAddress": "55 Sương Nguyệt Anh, Quận 1, Hồ Chí Minh",
    "tag": "Cafe sân vườn",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "40k-60k",
    "rating": 4.7,
    "reviews": 110,
    "hours": "08:00 - 21:00",
    "phone": "0908726784",
    "goodReview": "Không gian nhiều cây xanh, yên tĩnh và mát mẻ, phù hợp trò chuyện, đọc sách và làm việc.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Sân vườn",
      "Cây xanh",
      "Yên tĩnh",
      "Hẹn hò",
      "Làm việc"
    ],
    "desc": "Tiệm cây Người Làm Vườn kết hợp cafe với không gian cây xanh, tạo cảm giác như một khu vườn nhỏ giữa trung tâm Quận 1.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Đọc sách",
      "Chạy deadline",
      "Ngắm cây"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 20,
    "name": "RuNam d'Or",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "3 Công trường Công xã Paris, Quận 1, Hồ Chí Minh",
    "fullAddress": "3 Công trường Công xã Paris, Quận 1, Hồ Chí Minh",
    "tag": "Cafe sân vườn",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "100k+",
    "rating": 4.5,
    "reviews": 2727,
    "hours": "07:00 - 23:00",
    "phone": "02838292329",
    "goodReview": "Không gian ngoài trời kết hợp kiến trúc Pháp, nhiều cây xanh và vị trí lãng mạn cạnh Nhà thờ Đức Bà.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Sân vườn",
      "Ngoài trời",
      "Lãng mạn",
      "Hẹn hò",
      "Check-in"
    ],
    "desc": "RuNam d'Or nằm tại Công trường Công xã Paris, kết hợp không gian cafe trong nhà và ngoài trời trong khuôn viên kiến trúc Pháp.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Check-in",
      "Ngồi ngoài trời",
      "Trò chuyện"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJR6fQ6DcvdTERM4zSlXG2zhQ",
    "mapUrl": ""
  },
  {
    "id": 21,
    "name": "Oromia Coffee & Lounge",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "85 Phan Kế Bính, Quận 1, Hồ Chí Minh",
    "fullAddress": "85 Phan Kế Bính, Quận 1, Hồ Chí Minh",
    "tag": "Cafe sân vườn",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "50k-150k",
    "rating": 3.9,
    "reviews": 800,
    "hours": "07:00 - 23:00",
    "phone": "0988009232",
    "goodReview": "Không gian nhiều cây xanh, thiết kế đẹp và có khu vực ngoài trời phù hợp trò chuyện.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Sân vườn",
      "Cây xanh",
      "Hẹn hò",
      "Check-in",
      "Trò chuyện"
    ],
    "desc": "Oromia Coffee & Lounge là cafe có không gian sân vườn và nhiều cây xanh tại khu vực Phan Kế Bính.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Check-in",
      "Ngồi ngoài trời"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJT9IBetEpdTERv1WHWPOkMLo",
    "mapUrl": ""
  },
  {
    "id": 22,
    "name": "Cà phê trứng 3T - Garden Saigon",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "5 Trần Khánh Dư, Tân Định, Quận 1, Hồ Chí Minh",
    "fullAddress": "5 Trần Khánh Dư, Tân Định, Quận 1, Hồ Chí Minh",
    "tag": "Cafe sân vườn",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "50k-80k",
    "rating": 4.4,
    "reviews": 808,
    "hours": "07:00 - 23:00",
    "phone": "0865925670",
    "goodReview": "Không gian nhiều cây xanh, có khu garden ngoài trời, phong cách vintage và khá yên tĩnh.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Sân vườn",
      "Cây xanh",
      "Vintage",
      "Hẹn hò",
      "Làm việc"
    ],
    "desc": "Cà phê trứng 3T - Garden Saigon là cafe phong cách Việt hoài niệm với nhiều cây xanh và khu vực garden ngoài trời.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Uống cafe trứng",
      "Ngồi garden",
      "Làm việc"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJ133bTUApdTERwNR9Z6JzeoM",
    "mapUrl": ""
  },
  {
    "id": 23,
    "name": "1st. Garden - Cafe & Bistro",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "Tầng 3, Chung cư 26 Lý Tự Trọng, Bến Nghé, Quận 1, Hồ Chí Minh",
    "fullAddress": "Tầng 3, Chung cư 26 Lý Tự Trọng, Bến Nghé, Quận 1, Hồ Chí Minh",
    "tag": "Garden Cafe",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "25k-150k",
    "rating": 4.1,
    "reviews": 71,
    "hours": "09:00 - 22:30",
    "phone": "0908444003",
    "goodReview": "Không gian giống một khu vườn nhỏ trong chung cư cũ, có cây xanh lớn và ban công.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Garden",
      "Cây xanh",
      "Ban công",
      "Hẹn hò",
      "Check-in"
    ],
    "desc": "1st Garden là cafe nằm trên tầng 3 của chung cư 26 Lý Tự Trọng, được thiết kế theo concept khu vườn giữa trung tâm.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Check-in",
      "Ngồi ban công",
      "Trò chuyện"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 24,
    "name": "Khóm - Coffee & Tea",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "5 Trần Quý Khoách, Tân Định, Quận 1, Hồ Chí Minh",
    "fullAddress": "5 Trần Quý Khoách, Tân Định, Quận 1, Hồ Chí Minh",
    "tag": "Cafe sân vườn",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "50k-60k",
    "rating": null,
    "reviews": 16,
    "hours": "07:00 - 22:00",
    "phone": "",
    "goodReview": "Không gian mộc mạc với tre, nứa, gỗ và nhiều cây xanh, phù hợp cặp đôi và nhóm nhỏ.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Cây xanh",
      "Sân vườn",
      "Mộc mạc",
      "Hẹn hò",
      "Trò chuyện"
    ],
    "desc": "Khóm Coffee & Tea có phong cách mộc mạc, sử dụng tre, nứa và gỗ kết hợp cây xanh tạo cảm giác như một khu vườn nhỏ.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Trò chuyện",
      "Check-in"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 25,
    "name": "Pora Pora Coffee",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "Tầng 2, 7/13 Nguyễn Trãi, Bến Thành, Quận 1, Hồ Chí Minh",
    "fullAddress": "Tầng 2, 7/13 Nguyễn Trãi, Bến Thành, Quận 1, Hồ Chí Minh",
    "tag": "Garden Cafe",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "45k-60k",
    "rating": 4.3,
    "reviews": 12,
    "hours": "09:00 - 21:00",
    "phone": "",
    "goodReview": "Không gian có tầng ngoài trời/sân thượng, nhiều góc trang trí phù hợp cặp đôi và chụp ảnh.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Sân thượng",
      "Ngoài trời",
      "Cặp đôi",
      "Check-in",
      "Trò chuyện"
    ],
    "desc": "Pora Pora Coffee nằm trong hẻm Nguyễn Trãi, có không gian tầng 2 và khu vực ngoài trời.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Check-in",
      "Ngồi ngoài trời"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 26,
    "name": "Padma de Fleur",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "89/12 Hàm Nghi, Nguyễn Thái Bình, Quận 1, Hồ Chí Minh",
    "fullAddress": "89/12 Hàm Nghi, Nguyễn Thái Bình, Quận 1, Hồ Chí Minh",
    "tag": "Flower Cafe",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "45k-80k",
    "rating": 4.5,
    "reviews": 372,
    "hours": "09:00 - 18:00",
    "phone": "0336111315",
    "goodReview": "Cafe kết hợp tiệm hoa, không gian ngập cây và hoa, phù hợp hẹn hò và thư giãn.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Hoa",
      "Cây xanh",
      "Cafe",
      "Hẹn hò",
      "Lãng mạn"
    ],
    "desc": "Padma de Fleur kết hợp cafe với không gian hoa và cây xanh, tạo cảm giác như một khu vườn hoa nhỏ giữa Quận 1.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Ngắm hoa",
      "Uống cafe",
      "Chụp ảnh"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 27,
    "name": "Bâng Khuâng Cafe",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "Lầu 2, 9 Thái Văn Lung, Quận 1, Hồ Chí Minh",
    "fullAddress": "Lầu 2, 9 Thái Văn Lung, Quận 1, Hồ Chí Minh",
    "tag": "Cafe xanh",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "40k-110k",
    "rating": 4.3,
    "reviews": 649,
    "hours": "08:00 - 23:00",
    "phone": "0903667888",
    "goodReview": "Không gian yên tĩnh, phù hợp trò chuyện và thư giãn trong khu trung tâm.",
    "badReview": "",
    "hasBad": false,
    "viewDep": false,
    "tags": [
      "Yên tĩnh",
      "Cây xanh",
      "Hẹn hò",
      "Trò chuyện"
    ],
    "desc": "Bâng Khuâng Cafe nằm trên tầng 2 tại Thái Văn Lung, mang phong cách hoài niệm và yên tĩnh.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Trò chuyện",
      "Đọc sách"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 28,
    "name": "Cà Phê Cô Ba Đồng Khởi",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "2 Đồng Khởi, Quận 1, Hồ Chí Minh",
    "fullAddress": "2 Đồng Khởi, Quận 1, Hồ Chí Minh",
    "tag": "Cafe ban công",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "45k-60k",
    "rating": 4.3,
    "reviews": 1673,
    "hours": "07:30 - 23:00",
    "phone": "",
    "goodReview": "Cafe phong cách Sài Gòn xưa, có khu vực ban công và không gian mở phù hợp ngắm phố và hẹn hò.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Ban công",
      "Ngoài trời",
      "Vintage",
      "Hẹn hò",
      "Check-in"
    ],
    "desc": "Cà Phê Cô Ba Đồng Khởi nằm tại 2 Đồng Khởi, nổi bật với phong cách Sài Gòn xưa và khu vực ban công nhìn xuống phố.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Ngắm phố",
      "Check-in",
      "Trò chuyện"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJ-ccIKnwvdTERcwhsdEeX6cs",
    "mapUrl": ""
  },
  {
    "id": 29,
    "name": "rêu.coffee",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "46 Trịnh Văn Cấn, Quận 1, Hồ Chí Minh",
    "fullAddress": "46 Trịnh Văn Cấn, Quận 1, Hồ Chí Minh",
    "tag": "Cafe cây xanh",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "1-100k",
    "rating": 4.5,
    "reviews": 482,
    "hours": "07:00 - 01:00",
    "phone": "0966988815",
    "goodReview": "Cafe có phong cách xanh, không gian thư giãn và mở cửa đến khuya.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Cây xanh",
      "Late night",
      "Hẹn hò",
      "Trò chuyện",
      "Làm việc"
    ],
    "desc": "rêu.coffee là quán cafe tại Trịnh Văn Cấn với không gian xanh và thời gian hoạt động đến khuya.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Chạy deadline",
      "Ngồi khuya",
      "Trò chuyện"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJgyd46n4vdTEROUYGTQzVshc",
    "mapUrl": ""
  },
  {
    "id": 30,
    "name": "Cafe Tí Nị",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "5A Nguyễn Đình Chiểu, Quận 1, Hồ Chí Minh",
    "fullAddress": "5A Nguyễn Đình Chiểu, Quận 1, Hồ Chí Minh",
    "tag": "Cafe sân vườn",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "1-100k",
    "rating": 3.8,
    "reviews": 187,
    "hours": "07:00 - 21:00",
    "phone": "",
    "goodReview": "Cafe nhỏ, nhiều cây xanh và có không gian ngoài trời.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Sân vườn",
      "Cây xanh",
      "Yên tĩnh",
      "Trò chuyện"
    ],
    "desc": "Cafe Tí Nị là quán cafe nhỏ tại Nguyễn Đình Chiểu, được các nguồn tổng hợp cafe sân vườn Quận 1 nhắc tới.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Trò chuyện",
      "Ngồi ngoài trời"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "ChIJxyeRN7UodTERla8SNKpjpK0",
    "mapUrl": ""
  },
  {
    "id": 31,
    "name": "Tonkin Specialty Coffee Nguyễn Thái Bình",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "145 Nguyễn Thái Bình, Quận 1, Hồ Chí Minh",
    "fullAddress": "145 Nguyễn Thái Bình, Quận 1, Hồ Chí Minh",
    "tag": "Cafe xanh",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "50k-100k",
    "rating": null,
    "reviews": null,
    "hours": "",
    "phone": "",
    "goodReview": "Không gian mang phong cách Đông Dương, được các danh sách cafe sân vườn Quận 1 xếp vào nhóm cafe xanh.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Cây xanh",
      "Indochine",
      "Hẹn hò",
      "Check-in"
    ],
    "desc": "Tonkin Specialty Coffee là cafe phong cách Đông Dương được nhắc đến trong các danh sách cafe sân vườn Quận 1.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Check-in",
      "Trò chuyện"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  },
  {
    "id": 32,
    "name": "DABAO CONCEPT COFFEE",
    "district": "Quận 1",
    "group": "Quận 1",
    "address": "Phòng 37, Lầu 3, 145 Nguyễn Trãi, Quận 1, Hồ Chí Minh",
    "fullAddress": "Phòng 37, Lầu 3, 145 Nguyễn Trãi, Quận 1, Hồ Chí Minh",
    "tag": "Concept Cafe",
    "tagClass": "tag-garden",
    "category": "garden",
    "price": "40k-100k",
    "rating": null,
    "reviews": null,
    "hours": "09:00 - 21:00",
    "phone": "",
    "goodReview": "Cafe concept trong chung cư cũ với nhiều cây xanh và không gian mở, phù hợp check-in và hẹn hò.",
    "badReview": "",
    "hasBad": false,
    "viewDep": true,
    "tags": [
      "Cây xanh",
      "Concept",
      "Vintage",
      "Hẹn hò",
      "Check-in"
    ],
    "desc": "DABAO CONCEPT COFFEE nằm tại tầng 3 của chung cư 145 Nguyễn Trãi, có phong cách hoài cổ và nhiều mảng xanh.",
    "images": [],
    "quickActions": [
      "Đi date",
      "Check-in",
      "Trò chuyện"
    ],
    "menu": [],
    "reviewList": [],
    "geo": { "lat": null, "lng": null },
    "fsqId": "",
    "mapUrl": ""
  }
];

const currentSpots = JSON.parse(fs.readFileSync(GARDEN_FILE, 'utf8'));

// Filter out duplicates by name
const existingNames = new Set(currentSpots.map(s => s.name.toLowerCase().trim()));
const filteredNewGardens = newGardens.filter(s => !existingNames.has(s.name.toLowerCase().trim()));

const combined = [...currentSpots, ...filteredNewGardens];
combined.forEach((s, idx) => {
  s.id = idx + 1;
});

fs.writeFileSync(GARDEN_FILE, JSON.stringify(combined, null, 2), 'utf8');
console.log(`🎉 Combined garden.json now has ${combined.length} total spots (${filteredNewGardens.length} new District 1 garden spots added)!`);
